### ISSUE TITLE
lWHEMS-2 

### ISSUE THREAD

**Issue by djcutch** [rwoldberg/ldata-ha#11]
I had the plugin install for about 30 min and i am not seeing any data on my lwhems-2 main breaker.  Right now i do not have any smart breakers installed as i am waiting for the gen2 to fully come out.  Idk if you monitor the power of the mains.

**Comment by djcutch** [comment]
2023-12-18 17:04:55.012 DEBUG (SyncWorker_6) [ldata] Get WHEMS breakers result 200: []
2023-12-18 17:04:55.298 DEBUG (MainThread) [ldata] Finished fetching ldata data in 1.862 seconds (success: True)
2023-12-18 17:04:55.304 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ldata platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ldata/sensor.py", line 119, in async_setup_entry
    total_sensor = LDATATotalUsageSensor(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ldata/sensor.py", line 264, in __init__
    self._state = self.total_values()
                  ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ldata/sensor.py", line 283, in total_values
    return total / count
           ~~~~~~^~~~~~~
ZeroDivisionError: float division by zero
2023-12-18 17:05:08.672 WARNING (MainThread) [homeassistant.components.light] Updating decora_wifi light took longer than the scheduled update interval 0:00:30

**Comment by djcutch** [comment]
So updated i went and got one gen1 smart breaker this is able to capture the wattage and amp for the one breaker but not the whole panel.

**Comment by rwoldberg** [comment]
I will take a look at this over the holidays.  I don't have a WHEMS unit so I may or may not be able to fix it.

**Comment by djcutch** [comment]
> I will take a look at this over the holidays. I don't have a WHEMS unit so I may or may not be able to fix it.

If you need me to help diag this i am more then willing to help

**Comment by djcutch** [comment]
> I will take a look at this over the holidays. I don't have a WHEMS unit so I may or may not be able to fix it.

2023-12-19 17:17:07.033 DEBUG (SyncWorker_1) [ldata] Get WHEMS Panels result 200: [{"id":"1000_002F_A50C","name":"Main Breaker","anomalyOverride":true,"anomalyRefrigExcessEnergy":25,"anomalyRefrigLowEnergy":25,"anomalyRefrigExcessPower":25,"anomalyHVACExcessEnergy":50,"anomalyHVACLowEnergy":50,"anomalyHVACExcessPower":25,"anomalyRangeRunTime":240,"anomalyDisposalRunTime":3,"anomalyGeneralExcessPower":25,"anomalyGeneralLowPower":25,"anomalyStatus":null,"identify":0,"downloaded":"1.4.0","deviceCount":1,"manufacturer":"Leviton Manufacturing Co., Inc.","model":"LWHEM","serial":"1000_002F_A50C","version":"1.4.0","env":3,"connected":true,"localIP":"192.168.5.55","created":"2023-12-16T15:24:50.000Z","lastUpdated":"2023-12-19T22:17:07.000Z","rssi":-53,"residenceId":848439,"connectedTimestamp":"1702773528520","apply_ota":0,"otaStatus":0,"mac":"00:07:a6:37:c4:cb","logging":0,"channel1Active":true,"channel2Active":false,"channel3Active":false,"channel1Status":1,"channel2Status":0,"channel3Status":0,"bandwidth":2,"loadSheddingState":null,"diagnosticData":"","regKey":"","token":"0OTfWF5tAUNjXTbC0ChyHe2fWskEyFU3LlwgfiOixKh22o8XJnwuEYRtymTAHtTc","frequencyA":60,"frequencyB":60,"overVoltage":false,"overVoltageThreshold":132,"rmsVoltageA":124,"rmsVoltageB":124,"underVoltage":false,"underVoltageThreshold":102,"ccSetup1":0,"ccSetup2":0,"ccState1":false,"ccState2":false,"averageCurrentCount":10,"breakerCount":1,"commissioned":false,"whemReplaced":0,"whemReplacementData":null,"discoverBreakers":false,"discoverBreakersMode":null,"discoverBreakersStatus":"STOP","discoverBreakersTimeout":null,"driverData":"18326F55414444415500F4D4C86F321826E33B5F6443","errorCode":null,"factoryReset":false,"factoryResetBreaker":false,"factoryResetLSBMA":false,"orientation":0,"panelSize":66,"pollBreakers":null,"requestVersionHour":0,"resetEnergyConsumption":false,"status":"0","apply_ota_BLE":0,"otaStatusBLE":0,"versionBLE":"1.1.0","downloadedBLE":"1.1.0","wifiMode":null,"customNotifications":null,"replaceBreakerId":"","replaceBreakers":false,"replaceBreakerStatus":"","admin":0,"getSchedules":false}]
2023-12-19 17:17:07.519 DEBUG (SyncWorker_1) [ldata] Get WHEMS breakers result 200: 

looks like do you collect the data for the main breaker.

**Comment by djcutch** [comment]
So ive been toying with this looks like you have to add ldata for each breaker as well.  I do see in the log the feq data and voltage but it is missing on the breaker feild 
<img width="1041" alt="Screenshot 2023-12-19 210557" src="https://github.com/rwoldberg/ldata-ha/assets/46410638/c87e2d79-b8e6-4045-98d4-1a0f62aa11ac">
<img width="976" alt="Screenshot 2023-12-19 210615" src="https://github.com/rwoldberg/ldata-ha/assets/46410638/52f6d627-e0a9-40ef-af5d-dd3921a7e42f">

**Comment by rwoldberg** [comment]
I just pushed a release that should fix the divide by zero error.  Let me know if this fixes the issue.   The update will show up in home assistant sometime in the next day.  You can force it to update by clicking on ldata-ha integration in HACS then clicking the '...' in the upper right then selecting 'Update information', then you should see the update on the main HACS page.

**Comment by rwoldberg** [comment]
Also, you should not need to add an integration for each breaker, unless they are on separate accounts.

**Comment by djcutch** [comment]
> Also, you should not need to add an integration for each breaker, unless they are on separate accounts.

yeah i added the breaker a couple days after i got the lwhem looks like that why i had to.

**Comment by rwoldberg** [comment]
So its not picking up newly added breakers.  I might need to add code for that.  I'll have to figure that out.  I'm going to close this ticket since I think the divide by zero error is fixed.  You can open a new one if you find another issue.

**Comment by djcutch** [comment]
Great thank you looks better.  Should i open a new task so the main lwhem  data is being reported alone vs a calculated number based on breakers.

**Comment by rwoldberg** [comment]
Is this data that is reported by CT clamps?

**Comment by djcutch** [comment]
> Is this data that is reported by CT clamps?

yes

**Comment by rwoldberg** [comment]
So, I can't replace the accumulation data with the data from CT clamps, that would break all installs with the old device.  From what I understand, and this could be wrong, the CT clamps could be put on a different breaker, a non-smart one.  There might need to be some options to get this work correctly.   It will be a bit difficult to get it work without a new device.  I really need a LWHEM-2 and at least one gen2 breaker.

**Comment by djcutch** [comment]
> So, I can't replace the accumulation data with the data from CT clamps, that would break all installs with the old device. From what I understand, and this could be wrong, the CT clamps could be put on a different breaker, a non-smart one. There might need to be some options to get this work correctly. It will be a bit difficult to get it work without a new device. I really need a LWHEM-2 and at least one gen2 breaker.

Yeah i know what you mean i got a case open with them with issues with the lwhem and gen1 breakers that should be fix next week.

yeah in my case my clamps are on my mains feed to monitor the whole house.

**Comment by d235j** [comment]
It looks like the CT clamps that come with the LWHEMS are meant to be put only on the mains feed. However the LWHEMS has 2 additional inputs for CT clamps from other power sources, e.g. solar/generator/battery, to help support load shedding.

The CT clamps from the LWHEMS would be measuring the total power though, including any power being consumed by non-smart breakers, while the calculated power would only take into account smart breakers.

I currently have an LDATA; will probably upgrade in the future. The remote control / load-shedding functions of the LWHEMS and Gen 2 breakers look convenient, but device availability still isn't great.
