### ISSUE TITLE
home assistant arm64 host float error

### ISSUE THREAD

**Issue by gtxaspec** [rwoldberg/ldata-ha#6]
on an arm64 host, this error happens:

2023-05-11 17:09:22.387 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform ldata
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/ldata/sensor.py", line 179, in async_added_to_hass
    new_state = float(last_state.state)
ValueError: could not convert string to float: 'unknown'

doesn't happen on x86-64.

it causes energy usage, daily total, to not be updated on each device.

**Comment by rwoldberg** [comment]
I will try and prevent this from happening.  I don't have access to an arm64 device so it might take a while.

**Comment by gtxaspec** [comment]
@rwoldberg thank you for taking notice of this issue! 

i would be happy to test any changes, as my home assistant installation is not in production and I regularly wipe/reinstall for testing.

**Comment by rwoldberg** [comment]
This should be fixed in v 1.0.10. Let me know if it is not.

**Comment by gtxaspec** [comment]
works well.  thank you!
